dist: bionic
language: python

python:
  - '3.8'

addons:
  firefox: latest
  apt:
  packages:
    firefox-geckodriver
  # chrome: stable

branches:
  only:
    - staging
    - master

install:
  - pip3 install -r requirements.txt
  - pip3 install tchappui-webdrivers

before_script:
  - install-webdrivers

env: DJANGO_SETTINGS_MODULE="tec_et_art.settings.travis"

services:
  - postgresql

script:
  - python3 manage.py test editorial user design community
