# Generated by Django 3.1.3 on 2020-12-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_design_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='photo',
            new_name='design_image',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='product_name',
            new_name='design_name',
        ),
        migrations.AddField(
            model_name='design',
            name='plan_3d',
            field=models.FileField(default='default', upload_to='design_3d_plan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='design',
            name='assembly_instruction',
            field=models.FileField(upload_to='design_assy_ins'),
        ),
        migrations.AlterField(
            model_name='design',
            name='plan_2d',
            field=models.FileField(upload_to='design_2d_plan'),
        ),
    ]
