# Generated by Django 3.1.3 on 2020-12-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_auto_20201221_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='date_updated',
        ),
        migrations.AlterField(
            model_name='adduserinfo',
            name='street',
            field=models.CharField(max_length=50),
        ),
    ]
